"""empty message

Revision ID: 099a27b88983
Revises: 
Create Date: 2021-03-20 20:45:45.751353

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '099a27b88983'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request',
                    sa.Column('index', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('response_time', sa.Float(), nullable=True),
                    sa.Column('date', sa.DateTime(), nullable=True),
                    sa.Column('method', sa.String(length=128), nullable=True),
                    sa.Column('size', sa.Integer(), nullable=True),
                    sa.Column('status_code', sa.Integer(), nullable=True),
                    sa.Column('path', sa.String(length=128), nullable=True),
                    sa.Column('user_agent', sa.String(length=128), nullable=True),
                    sa.Column('remote_address', sa.String(length=128), nullable=True),
                    sa.Column('exception', sa.String(length=128), nullable=True),
                    sa.Column('referrer', sa.String(length=128), nullable=True),
                    sa.Column('browser', sa.String(length=128), nullable=True),
                    sa.Column('platform', sa.String(length=128), nullable=True),
                    sa.Column('mimetype', sa.String(length=128), nullable=True),
                    sa.PrimaryKeyConstraint('index')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('request')
    # ### end Alembic commands ###
