"""empty message

Revision ID: b18465f36418
Revises: bae3670ad80c
Create Date: 2023-01-21 08:55:25.533180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b18465f36418'
down_revision = 'bae3670ad80c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_private', sa.Boolean(), nullable=True))

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('repo_link_description', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('live_link_description', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('short_description', sa.String(length=1024), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('short_description')
        batch_op.drop_column('live_link_description')
        batch_op.drop_column('repo_link_description')

    with op.batch_alter_table('blog_post', schema=None) as batch_op:
        batch_op.drop_column('is_private')

    # ### end Alembic commands ###
